#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "ERROR:"
  echo "You can't commit directly to master branch"
  echo "Please create a new branch and commit your changes to it"
  exit 1
fi